package ase_source_bak;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.GridBagConstraints;

import javax.swing.JLabel;

import java.awt.Insets;
import java.awt.GridBagLayout;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.JComboBox;

/**
 * This was a quick throw together to provide an easy way to access the data stored
 * for sounds, soundscapes, and keywords. It lacks polish and is just intended to
 * provide function.
 * <br>
 * <br>
 * 11/26/2015 - CKidwell - Changes made in order to show and allow changes
 * to the new fields of the sound object.
 */
public class ChangeDB extends javax.swing.JFrame {

	private static final long serialVersionUID = -1250532317858267571L;
	public ChangeDB() {
        initComponents();
        if(OperationsManager.db != null) {
	        ssList.setListData(OperationsManager.db.showTable("soundscape", "name"));
	        sfxList.setListData(OperationsManager.db.showTable("sound_file", "name"));
	        kwList.setListData(OperationsManager.db.showTable("keyword", "keyword"));
        } else {
        	String[] ndf = {"No database found"};
        	ssList.setListData(ndf);
        	ssList.setEnabled(false);
        	sfxList.setListData(ndf);
        	sfxList.setEnabled(false);
        	kwList.setListData(ndf);
        	kwList.setEnabled(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ssTab = new javax.swing.JPanel();
        ssSelectPanel = new javax.swing.JPanel();
        ssScroll = new javax.swing.JScrollPane();
        ssList = new javax.swing.JList<String>();
        ssDataPanel = new javax.swing.JPanel();
        ssIdLabel = new javax.swing.JLabel();
        ssIdBox = new javax.swing.JTextField();
        ssNameLabel = new javax.swing.JLabel();
        ssNameBox = new javax.swing.JTextField();
        ssDescriptionLabel = new javax.swing.JLabel();
        ssDescriptionBox = new javax.swing.JTextField();
        ssVolumeLabel = new javax.swing.JLabel();
        ssVolumeBox = new javax.swing.JTextField();
        ssIdDbLabel = new javax.swing.JLabel();
        ssIdDbBox = new javax.swing.JTextField();
        ssNameDbLabel = new javax.swing.JLabel();
        ssNameDbBox = new javax.swing.JTextField();
        ssDescriptionDbLabel = new javax.swing.JLabel();
        ssDescriptionDbBox = new javax.swing.JTextField();
        ssVolumeDbLabel = new javax.swing.JLabel();
        ssChangeDataLabel = new javax.swing.JLabel();
        ssDatabaseDataLabel = new javax.swing.JLabel();
        ssSaveButton = new javax.swing.JButton();
        ssVolumeDbBox = new javax.swing.JTextField();
        ssCancelButton = new javax.swing.JButton();
        sfxTab = new javax.swing.JPanel();
        sfxSelectPanel = new javax.swing.JPanel();
        sfxScroll = new javax.swing.JScrollPane();
        sfxList = new javax.swing.JList<String>();
        sfxDataPanel = new javax.swing.JPanel();
        sfxIdLabel = new javax.swing.JLabel();
        sfxIdBox = new javax.swing.JTextField();
        sfxNameLabel = new javax.swing.JLabel();
        sfxNameBox = new javax.swing.JTextField();
        sfxDescriptionLabel = new javax.swing.JLabel();
        sfxDescriptionBox = new javax.swing.JTextField();
        sfxDataLabel = new javax.swing.JLabel();
        sfxDataBox = new javax.swing.JTextField();
        sfxLengthLabel = new javax.swing.JLabel();
        sfxLengthBox = new javax.swing.JTextField();
        sfxLengthBox.setEnabled(false);
        sfxOwnerLabel = new javax.swing.JLabel();
        sfxOwnerBox = new javax.swing.JTextField();
        sfxCopyrightLabel = new javax.swing.JLabel();
        sfxPathLabel = new javax.swing.JLabel();
        sfxPathBox = new javax.swing.JTextField();
        sfxSizeLabel = new javax.swing.JLabel();
        sfxSizeBox = new javax.swing.JTextField();
        sfxSizeBox.setEnabled(false);
        sfxIdDbLabel = new javax.swing.JLabel();
        sfxIdDbBox = new javax.swing.JTextField();
        sfxNameDbLabel = new javax.swing.JLabel();
        sfxNameDbBox = new javax.swing.JTextField();
        sfxDescriptionDbLabel = new javax.swing.JLabel();
        sfxDescriptionDbBox = new javax.swing.JTextField();
        sfxDataDbLabel = new javax.swing.JLabel();
        sfxDataDbBox = new javax.swing.JTextField();
        sfxLengthDbLabel = new javax.swing.JLabel();
        sfxLengthDbBox = new javax.swing.JTextField();
        sfxOwnerDbLabel = new javax.swing.JLabel();
        sfxOwnerDbBox = new javax.swing.JTextField();
        sfxCopyrightDbLabel = new javax.swing.JLabel();
        sfxPathDbLabel = new javax.swing.JLabel();
        sfxPathDbBox = new javax.swing.JTextField();
        sfxSizeDbLabel = new javax.swing.JLabel();
        sfxSizeDbBox = new javax.swing.JTextField();
        sfxChangeDataLabel = new javax.swing.JLabel();
        sfxDatabaseDataLabel = new javax.swing.JLabel();
        sfxSaveButton = new javax.swing.JButton();
        sfxCancelButton = new javax.swing.JButton();
        kwTab = new javax.swing.JPanel();
        kwSelectPanel = new javax.swing.JPanel();
        kwScroll = new javax.swing.JScrollPane();
        kwList = new javax.swing.JList<String>();
        kwDataPanel = new javax.swing.JPanel();
        kwIdBox = new javax.swing.JTextField();
        kwNameBox = new javax.swing.JTextField();
        kwIdLabel = new javax.swing.JLabel();
        kwNameLabel = new javax.swing.JLabel();
        kwIdDbBox = new javax.swing.JTextField();
        kwNameDbBox = new javax.swing.JTextField();
        kwIdDbLabel = new javax.swing.JLabel();
        kwNameDbLabel = new javax.swing.JLabel();
        kwChangeDataLabel = new javax.swing.JLabel();
        kwDatabaseDataLabel = new javax.swing.JLabel();
        kwSaveButton = new javax.swing.JButton();
        kwCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(150, 100));
        ssTab.setLayout(new java.awt.GridBagLayout());

        ssSelectPanel.setLayout(new java.awt.GridBagLayout());

        ssSelectPanel.setPreferredSize(new java.awt.Dimension(170, 470));
        ssScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ssScroll.setFont(new java.awt.Font("Arial", 0, 11));
        ssScroll.setPreferredSize(new java.awt.Dimension(145, 450));
        ssList.setFont(new java.awt.Font("Arial", 0, 12));
        ssList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ssList.setPreferredSize(null);
        ssList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ssListValueChanged(evt);
            }
        });
        ssList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssListMouseClicked(evt);
            }
        });

        ssScroll.setViewportView(ssList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ssSelectPanel.add(ssScroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        ssTab.add(ssSelectPanel, gridBagConstraints);

        ssDataPanel.setLayout(new java.awt.GridBagLayout());

        ssDataPanel.setMinimumSize(new java.awt.Dimension(540, 80));
        ssDataPanel.setPreferredSize(new java.awt.Dimension(550, 460));
        ssIdLabel.setText("Soundscape ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        ssDataPanel.add(ssIdLabel, gridBagConstraints);

        ssIdBox.setEnabled(false);
        ssIdBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        ssDataPanel.add(ssIdBox, gridBagConstraints);

        ssNameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        ssDataPanel.add(ssNameLabel, gridBagConstraints);

        ssNameBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ssDataPanel.add(ssNameBox, gridBagConstraints);

        ssDescriptionLabel.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        ssDataPanel.add(ssDescriptionLabel, gridBagConstraints);

        ssDescriptionBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ssDataPanel.add(ssDescriptionBox, gridBagConstraints);

        ssVolumeLabel.setText("Volume:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        ssDataPanel.add(ssVolumeLabel, gridBagConstraints);

        ssVolumeBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ssDataPanel.add(ssVolumeBox, gridBagConstraints);

        ssIdDbLabel.setText("Soundscape ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        ssDataPanel.add(ssIdDbLabel, gridBagConstraints);

        ssIdDbBox.setEnabled(false);
        ssIdDbBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ssDataPanel.add(ssIdDbBox, gridBagConstraints);

        ssNameDbLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        ssDataPanel.add(ssNameDbLabel, gridBagConstraints);

        ssNameDbBox.setEnabled(false);
        ssNameDbBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ssDataPanel.add(ssNameDbBox, gridBagConstraints);

        ssDescriptionDbLabel.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        ssDataPanel.add(ssDescriptionDbLabel, gridBagConstraints);

        ssDescriptionDbBox.setEnabled(false);
        ssDescriptionDbBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        ssDataPanel.add(ssDescriptionDbBox, gridBagConstraints);

        ssVolumeDbLabel.setText("Volume:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        ssDataPanel.add(ssVolumeDbLabel, gridBagConstraints);

        ssChangeDataLabel.setText("Change Soundscape Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        ssDataPanel.add(ssChangeDataLabel, gridBagConstraints);

        ssDatabaseDataLabel.setText("Database Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        ssDataPanel.add(ssDatabaseDataLabel, gridBagConstraints);

        ssSaveButton.setText("Save Changes");
        ssSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssSaveButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        ssDataPanel.add(ssSaveButton, gridBagConstraints);

        ssVolumeDbBox.setEnabled(false);
        ssVolumeDbBox.setPreferredSize(new java.awt.Dimension(165, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        ssDataPanel.add(ssVolumeDbBox, gridBagConstraints);

        ssCancelButton.setText("Cancel Changes");
        ssCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssCancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        ssDataPanel.add(ssCancelButton, gridBagConstraints);

        ssTab.add(ssDataPanel, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Soundscapes", ssTab);

        sfxTab.setLayout(new java.awt.GridBagLayout());

        sfxSelectPanel.setLayout(new java.awt.GridBagLayout());

        sfxSelectPanel.setPreferredSize(new java.awt.Dimension(170, 470));
        sfxScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sfxScroll.setFont(new java.awt.Font("Arial", 0, 11));
        sfxScroll.setPreferredSize(new java.awt.Dimension(145, 450));
        sfxList.setFont(new java.awt.Font("Arial", 0, 12));
        sfxList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sfxList.setPreferredSize(null);
        sfxList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sfxListValueChanged(evt);
            }
        });
        sfxList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sfxListMouseClicked(evt);
            }
        });

        sfxScroll.setViewportView(sfxList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        sfxSelectPanel.add(sfxScroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        sfxTab.add(sfxSelectPanel, gridBagConstraints);

        GridBagLayout gbl_sfxDataPanel = new GridBagLayout();
        gbl_sfxDataPanel.columnWeights = new double[]{0.0, 1.0, 0.0, 1.0};
        gbl_sfxDataPanel.columnWidths = new int[]{0, 175, 0, 175};
        sfxDataPanel.setLayout(gbl_sfxDataPanel);

        sfxDataPanel.setPreferredSize(new java.awt.Dimension(540, 460));
        sfxIdLabel.setText("Sound File Id:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxIdLabel, gridBagConstraints);

        sfxIdBox.setEnabled(false);
        sfxIdBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_30 = new java.awt.GridBagConstraints();
        gridBagConstraints_30.weightx = 1.0;
        gridBagConstraints_30.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_30.gridx = 1;
        gridBagConstraints_30.gridy = 1;
        gridBagConstraints_30.insets = new Insets(0, 0, 5, 5);
        sfxDataPanel.add(sfxIdBox, gridBagConstraints_30);

        sfxNameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxNameLabel, gridBagConstraints);

        sfxNameBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_2 = new java.awt.GridBagConstraints();
        gridBagConstraints_2.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_2.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_2.gridx = 1;
        gridBagConstraints_2.gridy = 2;
        sfxDataPanel.add(sfxNameBox, gridBagConstraints_2);

        sfxDescriptionLabel.setText("Notes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxDescriptionLabel, gridBagConstraints);

        sfxDescriptionBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_3 = new java.awt.GridBagConstraints();
        gridBagConstraints_3.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_3.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_3.gridx = 1;
        gridBagConstraints_3.gridy = 3;
        sfxDataPanel.add(sfxDescriptionBox, gridBagConstraints_3);

        sfxDataLabel.setText("Data File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxDataLabel, gridBagConstraints);

        sfxDataBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_4 = new java.awt.GridBagConstraints();
        gridBagConstraints_4.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_4.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_4.gridx = 1;
        gridBagConstraints_4.gridy = 4;
        sfxDataPanel.add(sfxDataBox, gridBagConstraints_4);

        sfxLengthLabel.setText("Length:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxLengthLabel, gridBagConstraints);

        sfxLengthBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_5 = new java.awt.GridBagConstraints();
        gridBagConstraints_5.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_5.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_5.gridx = 1;
        gridBagConstraints_5.gridy = 5;
        sfxDataPanel.add(sfxLengthBox, gridBagConstraints_5);

        sfxOwnerLabel.setText("Created By:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxOwnerLabel, gridBagConstraints);

        sfxOwnerBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_6 = new java.awt.GridBagConstraints();
        gridBagConstraints_6.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_6.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_6.gridx = 1;
        gridBagConstraints_6.gridy = 6;
        sfxDataPanel.add(sfxOwnerBox, gridBagConstraints_6);

        sfxCopyrightLabel.setText("Copyright:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxCopyrightLabel, gridBagConstraints);
        
        sfxComboBoxCopyright = new JComboBox<String>();
        ComboBoxModel<String> model = new DefaultComboBoxModel<String>(SoundObject.comboBoxOptions);
        sfxComboBoxCopyright.setModel(model);
        GridBagConstraints gbc_comboBox = new GridBagConstraints();
        gbc_comboBox.insets = new Insets(0, 0, 5, 5);
        gbc_comboBox.fill = GridBagConstraints.HORIZONTAL;
        gbc_comboBox.gridx = 1;
        gbc_comboBox.gridy = 7;
        sfxDataPanel.add(sfxComboBoxCopyright, gbc_comboBox);
        
        sfxComboBoxCopyrightDb = new JComboBox<String>();
        ComboBoxModel<String> model2 = new DefaultComboBoxModel<String>(SoundObject.comboBoxOptions);
		sfxComboBoxCopyrightDb.setModel(model2);
		sfxComboBoxCopyrightDb.setEnabled(false);
        GridBagConstraints gbc_comboBox_1 = new GridBagConstraints();
        gbc_comboBox_1.insets = new Insets(0, 0, 5, 0);
        gbc_comboBox_1.fill = GridBagConstraints.HORIZONTAL;
        gbc_comboBox_1.gridx = 3;
        gbc_comboBox_1.gridy = 7;
        sfxDataPanel.add(sfxComboBoxCopyrightDb, gbc_comboBox_1);

        sfxPathLabel.setText("File Path:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxPathLabel, gridBagConstraints);

        sfxPathBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_8 = new java.awt.GridBagConstraints();
        gridBagConstraints_8.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_8.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_8.gridx = 1;
        gridBagConstraints_8.gridy = 8;
        sfxDataPanel.add(sfxPathBox, gridBagConstraints_8);

        sfxSizeLabel.setText("File Size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(5, 0, 5, 5);
        sfxDataPanel.add(sfxSizeLabel, gridBagConstraints);

        sfxSizeBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_9 = new java.awt.GridBagConstraints();
        gridBagConstraints_9.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_9.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_9.gridx = 1;
        gridBagConstraints_9.gridy = 9;
        sfxDataPanel.add(sfxSizeBox, gridBagConstraints_9);

        sfxIdDbLabel.setText("Sound File ID:");
        gridBagConstraints_10 = new java.awt.GridBagConstraints();
        gridBagConstraints_10.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_10.gridx = 2;
        gridBagConstraints_10.gridy = 1;
        gridBagConstraints_10.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxIdDbLabel, gridBagConstraints_10);

        sfxIdDbBox.setEnabled(false);
        sfxIdDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_11 = new java.awt.GridBagConstraints();
        gridBagConstraints_11.weightx = 1.0;
        gridBagConstraints_11.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_11.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_11.gridx = 3;
        gridBagConstraints_11.gridy = 1;
        sfxDataPanel.add(sfxIdDbBox, gridBagConstraints_11);

        sfxNameDbLabel.setText("Name:");
        gridBagConstraints_12 = new java.awt.GridBagConstraints();
        gridBagConstraints_12.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_12.gridx = 2;
        gridBagConstraints_12.gridy = 2;
        gridBagConstraints_12.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxNameDbLabel, gridBagConstraints_12);

        sfxNameDbBox.setEnabled(false);
        sfxNameDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_13 = new java.awt.GridBagConstraints();
        gridBagConstraints_13.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_13.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_13.gridx = 3;
        gridBagConstraints_13.gridy = 2;
        sfxDataPanel.add(sfxNameDbBox, gridBagConstraints_13);

        sfxDescriptionDbLabel.setText("Notes:");
        gridBagConstraints_14 = new java.awt.GridBagConstraints();
        gridBagConstraints_14.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_14.gridx = 2;
        gridBagConstraints_14.gridy = 3;
        gridBagConstraints_14.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxDescriptionDbLabel, gridBagConstraints_14);

        sfxDescriptionDbBox.setEnabled(false);
        sfxDescriptionDbBox.setMinimumSize(new java.awt.Dimension(95, 19));
        sfxDescriptionDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_15 = new java.awt.GridBagConstraints();
        gridBagConstraints_15.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_15.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_15.gridx = 3;
        gridBagConstraints_15.gridy = 3;
        sfxDataPanel.add(sfxDescriptionDbBox, gridBagConstraints_15);

        sfxDataDbLabel.setText("Data File:");
        gridBagConstraints_16 = new java.awt.GridBagConstraints();
        gridBagConstraints_16.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_16.gridx = 2;
        gridBagConstraints_16.gridy = 4;
        gridBagConstraints_16.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxDataDbLabel, gridBagConstraints_16);

        sfxDataDbBox.setEnabled(false);
        sfxDataDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_17 = new java.awt.GridBagConstraints();
        gridBagConstraints_17.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_17.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_17.gridx = 3;
        gridBagConstraints_17.gridy = 4;
        sfxDataPanel.add(sfxDataDbBox, gridBagConstraints_17);

        sfxLengthDbLabel.setText("Length:");
        gridBagConstraints_18 = new java.awt.GridBagConstraints();
        gridBagConstraints_18.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_18.gridx = 2;
        gridBagConstraints_18.gridy = 5;
        gridBagConstraints_18.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxLengthDbLabel, gridBagConstraints_18);

        sfxLengthDbBox.setEnabled(false);
        sfxLengthDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_19 = new java.awt.GridBagConstraints();
        gridBagConstraints_19.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_19.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_19.gridx = 3;
        gridBagConstraints_19.gridy = 5;
        sfxDataPanel.add(sfxLengthDbBox, gridBagConstraints_19);

        sfxOwnerDbLabel.setText("Created By:");
        gridBagConstraints_20 = new java.awt.GridBagConstraints();
        gridBagConstraints_20.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_20.gridx = 2;
        gridBagConstraints_20.gridy = 6;
        gridBagConstraints_20.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxOwnerDbLabel, gridBagConstraints_20);

        sfxOwnerDbBox.setEnabled(false);
        sfxOwnerDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_21 = new java.awt.GridBagConstraints();
        gridBagConstraints_21.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_21.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_21.gridx = 3;
        gridBagConstraints_21.gridy = 6;
        sfxDataPanel.add(sfxOwnerDbBox, gridBagConstraints_21);

        sfxCopyrightDbLabel.setText("Copyright:");
        gridBagConstraints_22 = new java.awt.GridBagConstraints();
        gridBagConstraints_22.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_22.gridx = 2;
        gridBagConstraints_22.gridy = 7;
        gridBagConstraints_22.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxCopyrightDbLabel, gridBagConstraints_22);

        sfxPathDbLabel.setText("File Path:");
        gridBagConstraints_24 = new java.awt.GridBagConstraints();
        gridBagConstraints_24.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_24.gridx = 2;
        gridBagConstraints_24.gridy = 8;
        gridBagConstraints_24.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxPathDbLabel, gridBagConstraints_24);

        sfxPathDbBox.setEnabled(false);
        sfxPathDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_25 = new java.awt.GridBagConstraints();
        gridBagConstraints_25.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_25.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_25.gridx = 3;
        gridBagConstraints_25.gridy = 8;
        sfxDataPanel.add(sfxPathDbBox, gridBagConstraints_25);

        sfxSizeDbLabel.setText("File Size:");
        gridBagConstraints_26 = new java.awt.GridBagConstraints();
        gridBagConstraints_26.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_26.gridx = 2;
        gridBagConstraints_26.gridy = 9;
        gridBagConstraints_26.anchor = java.awt.GridBagConstraints.EAST;
        sfxDataPanel.add(sfxSizeDbLabel, gridBagConstraints_26);

        sfxSizeDbBox.setEnabled(false);
        sfxSizeDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints_27 = new java.awt.GridBagConstraints();
        gridBagConstraints_27.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints_27.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_27.gridx = 3;
        gridBagConstraints_27.gridy = 9;
        sfxDataPanel.add(sfxSizeDbBox, gridBagConstraints_27);

        sfxChangeDataLabel.setText("Change Sound Data");
        gridBagConstraints_1 = new java.awt.GridBagConstraints();
        gridBagConstraints_1.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints_1.gridx = 0;
        gridBagConstraints_1.gridy = 0;
        gridBagConstraints_1.gridwidth = 2;
        sfxDataPanel.add(sfxChangeDataLabel, gridBagConstraints_1);

        sfxDatabaseDataLabel.setText("Database Data");
        gridBagConstraints_28 = new java.awt.GridBagConstraints();
        gridBagConstraints_28.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_28.gridx = 2;
        gridBagConstraints_28.gridy = 0;
        gridBagConstraints_28.gridwidth = 2;
        sfxDataPanel.add(sfxDatabaseDataLabel, gridBagConstraints_28);

        sfxSaveButton.setText("Save Changes");
        sfxSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfxSaveButtonActionPerformed(evt);
            }
        });
        
        sfxLblImportedBy = new JLabel("Imported By:");
        GridBagConstraints gbc_lblImportedBy = new GridBagConstraints();
        gbc_lblImportedBy.anchor = GridBagConstraints.EAST;
        gbc_lblImportedBy.insets = new Insets(5, 0, 5, 5);
        gbc_lblImportedBy.gridx = 0;
        gbc_lblImportedBy.gridy = 10;
        sfxDataPanel.add(sfxLblImportedBy, gbc_lblImportedBy);
        
        sfxTxtImportedBy = new JTextField();
        sfxTxtImportedBy.setPreferredSize(new java.awt.Dimension(175, 19));
        GridBagConstraints gbc_txtImportedBy = new GridBagConstraints();
        gbc_txtImportedBy.insets = new Insets(0, 0, 5, 5);
        gbc_txtImportedBy.fill = GridBagConstraints.HORIZONTAL;
        gbc_txtImportedBy.gridx = 1;
        gbc_txtImportedBy.gridy = 10;
        sfxDataPanel.add(sfxTxtImportedBy, gbc_txtImportedBy);
        sfxTxtImportedBy.setColumns(10);
        
        sfxLblImportedByDb = new JLabel("Imported By:");
        GridBagConstraints gbc_lblImportedBy_1 = new GridBagConstraints();
        gbc_lblImportedBy_1.anchor = GridBagConstraints.EAST;
        gbc_lblImportedBy_1.insets = new Insets(5, 0, 5, 5);
        gbc_lblImportedBy_1.gridx = 2;
        gbc_lblImportedBy_1.gridy = 10;
        sfxDataPanel.add(sfxLblImportedByDb, gbc_lblImportedBy_1);
        
        sfxTxtImportedByDb = new JTextField();
        sfxTxtImportedByDb.setEnabled(false);
        sfxTxtImportedByDb.setPreferredSize(new java.awt.Dimension(175, 19));
        GridBagConstraints gbc_txtImportedByDb = new GridBagConstraints();
        gbc_txtImportedByDb.insets = new Insets(0, 0, 5, 0);
        gbc_txtImportedByDb.fill = GridBagConstraints.HORIZONTAL;
        gbc_txtImportedByDb.gridx = 3;
        gbc_txtImportedByDb.gridy = 10;
        sfxDataPanel.add(sfxTxtImportedByDb, gbc_txtImportedByDb);
        sfxTxtImportedByDb.setColumns(10);
        
        sfxLblSource = new JLabel("Source:");
        GridBagConstraints gbc_lblSource = new GridBagConstraints();
        gbc_lblSource.anchor = GridBagConstraints.EAST;
        gbc_lblSource.insets = new Insets(5, 0, 5, 5);
        gbc_lblSource.gridx = 0;
        gbc_lblSource.gridy = 11;
        sfxDataPanel.add(sfxLblSource, gbc_lblSource);
        
        sfxTxtSource = new JTextField();
        sfxTxtSource.setPreferredSize(new java.awt.Dimension(175, 19));
        GridBagConstraints gbc_txtSource = new GridBagConstraints();
        gbc_txtSource.insets = new Insets(0, 0, 5, 5);
        gbc_txtSource.fill = GridBagConstraints.HORIZONTAL;
        gbc_txtSource.gridx = 1;
        gbc_txtSource.gridy = 11;
        sfxDataPanel.add(sfxTxtSource, gbc_txtSource);
        sfxTxtSource.setColumns(10);
        
        sfxlblSourceDb = new JLabel("Source:");
        GridBagConstraints gbc_lblSource_1 = new GridBagConstraints();
        gbc_lblSource_1.anchor = GridBagConstraints.EAST;
        gbc_lblSource_1.insets = new Insets(5, 0, 5, 5);
        gbc_lblSource_1.gridx = 2;
        gbc_lblSource_1.gridy = 11;
        sfxDataPanel.add(sfxlblSourceDb, gbc_lblSource_1);
        
        sfxTxtSourceDb = new JTextField();
        sfxTxtSourceDb.setEnabled(false);
        sfxTxtSourceDb.setPreferredSize(new java.awt.Dimension(175, 19));
        GridBagConstraints gbc_txtSourceDb = new GridBagConstraints();
        gbc_txtSourceDb.insets = new Insets(0, 0, 5, 0);
        gbc_txtSourceDb.fill = GridBagConstraints.HORIZONTAL;
        gbc_txtSourceDb.gridx = 3;
        gbc_txtSourceDb.gridy = 11;
        sfxDataPanel.add(sfxTxtSourceDb, gbc_txtSourceDb);
        sfxTxtSourceDb.setColumns(10);
        
        sfxLblEditedBy = new JLabel("Edited By:");
        GridBagConstraints gbc_lblEditedBy = new GridBagConstraints();
        gbc_lblEditedBy.anchor = GridBagConstraints.EAST;
        gbc_lblEditedBy.insets = new Insets(5, 0, 5, 5);
        gbc_lblEditedBy.gridx = 0;
        gbc_lblEditedBy.gridy = 12;
        sfxDataPanel.add(sfxLblEditedBy, gbc_lblEditedBy);
        
        sfxTxtEditedBy = new JTextField();
        sfxTxtEditedBy.setPreferredSize(new java.awt.Dimension(175, 19));
        GridBagConstraints gbc_txtEditedBy = new GridBagConstraints();
        gbc_txtEditedBy.insets = new Insets(0, 0, 5, 5);
        gbc_txtEditedBy.fill = GridBagConstraints.HORIZONTAL;
        gbc_txtEditedBy.gridx = 1;
        gbc_txtEditedBy.gridy = 12;
        sfxDataPanel.add(sfxTxtEditedBy, gbc_txtEditedBy);
        sfxTxtEditedBy.setColumns(10);
        
        sfxLblEditedByDb = new JLabel("Edited By:");
        GridBagConstraints gbc_lblEditedBy_1 = new GridBagConstraints();
        gbc_lblEditedBy_1.anchor = GridBagConstraints.EAST;
        gbc_lblEditedBy_1.insets = new Insets(5, 0, 5, 5);
        gbc_lblEditedBy_1.gridx = 2;
        gbc_lblEditedBy_1.gridy = 12;
        sfxDataPanel.add(sfxLblEditedByDb, gbc_lblEditedBy_1);
        
        sfxTxtEditedByDb = new JTextField();
        sfxTxtEditedByDb.setEnabled(false);
        sfxTxtEditedByDb.setPreferredSize(new java.awt.Dimension(175, 19));
        GridBagConstraints gbc_txtEditedByDb = new GridBagConstraints();
        gbc_txtEditedByDb.insets = new Insets(0, 0, 5, 0);
        gbc_txtEditedByDb.fill = GridBagConstraints.HORIZONTAL;
        gbc_txtEditedByDb.gridx = 3;
        gbc_txtEditedByDb.gridy = 12;
        sfxDataPanel.add(sfxTxtEditedByDb, gbc_txtEditedByDb);
        sfxTxtEditedByDb.setColumns(10);

        gridBagConstraints_29 = new java.awt.GridBagConstraints();
        gridBagConstraints_29.insets = new Insets(0, 0, 0, 5);
        gridBagConstraints_29.gridx = 0;
        gridBagConstraints_29.gridy = 13;
        gridBagConstraints_29.gridwidth = 2;
        sfxDataPanel.add(sfxSaveButton, gridBagConstraints_29);

        sfxCancelButton.setText("Cancel Changes");
        sfxCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfxCancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        sfxDataPanel.add(sfxCancelButton, gridBagConstraints);

        sfxTab.add(sfxDataPanel, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Sounds", sfxTab);

        kwTab.setLayout(new java.awt.GridBagLayout());

        kwSelectPanel.setLayout(new java.awt.GridBagLayout());

        kwSelectPanel.setPreferredSize(new java.awt.Dimension(170, 470));
        kwScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        kwScroll.setFont(new java.awt.Font("Arial", 0, 11));
        kwScroll.setPreferredSize(new java.awt.Dimension(145, 450));
        kwList.setFont(new java.awt.Font("Arial", 0, 12));
        kwList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        kwList.setPreferredSize(null);
        kwList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                kwListValueChanged(evt);
            }
        });
        kwList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kwListMouseClicked(evt);
            }
        });

        kwScroll.setViewportView(kwList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        kwSelectPanel.add(kwScroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        kwTab.add(kwSelectPanel, gridBagConstraints);

        kwDataPanel.setLayout(new java.awt.GridBagLayout());

        kwDataPanel.setPreferredSize(new java.awt.Dimension(540, 460));
        kwIdBox.setEnabled(false);
        kwIdBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        kwDataPanel.add(kwIdBox, gridBagConstraints);

        kwNameBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        kwDataPanel.add(kwNameBox, gridBagConstraints);

        kwIdLabel.setText("Keyword Id:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        kwDataPanel.add(kwIdLabel, gridBagConstraints);

        kwNameLabel.setText("Keyword:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        kwDataPanel.add(kwNameLabel, gridBagConstraints);

        kwIdDbBox.setEnabled(false);
        kwIdDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        kwDataPanel.add(kwIdDbBox, gridBagConstraints);

        kwNameDbBox.setEnabled(false);
        kwNameDbBox.setPreferredSize(new java.awt.Dimension(175, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        kwDataPanel.add(kwNameDbBox, gridBagConstraints);

        kwIdDbLabel.setText("Keyword Id:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        kwDataPanel.add(kwIdDbLabel, gridBagConstraints);

        kwNameDbLabel.setText("Keyword:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        kwDataPanel.add(kwNameDbLabel, gridBagConstraints);

        kwChangeDataLabel.setText("Change Keyword Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        kwDataPanel.add(kwChangeDataLabel, gridBagConstraints);

        kwDatabaseDataLabel.setText("Database Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        kwDataPanel.add(kwDatabaseDataLabel, gridBagConstraints);

        kwSaveButton.setText("Save Changes");
        kwSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwSaveButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        kwDataPanel.add(kwSaveButton, gridBagConstraints);

        kwCancelButton.setText("Cancel Changes");
        kwCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwCancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        kwDataPanel.add(kwCancelButton, gridBagConstraints);

        kwTab.add(kwDataPanel, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("Keywords", kwTab);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Reverts the data for this keyword to the data stored in the db
     * @param evt
     */
    private void kwCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        kwIdBox.setText(kwIdDbBox.getText());
        kwNameBox.setText(kwNameDbBox.getText());
    }

    /**
     * Reverts the data for this sound file to the data in the db
     * @param evt
     */
    private void sfxCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        sfxIdBox.setText(sfxIdDbBox.getText());
        sfxNameBox.setText(sfxNameDbBox.getText());
        sfxDescriptionBox.setText(sfxDescriptionDbBox.getText());
        sfxDataBox.setText(sfxDataDbBox.getText());
        sfxLengthBox.setText(sfxLengthDbBox.getText());
        sfxOwnerBox.setText(sfxOwnerDbBox.getText());
        sfxComboBoxCopyright.setSelectedIndex(sfxComboBoxCopyrightDb.getSelectedIndex());
        sfxPathBox.setText(sfxPathDbBox.getText());
        sfxSizeBox.setText(sfxSizeDbBox.getText());
        sfxTxtImportedBy.setText(sfxTxtImportedByDb.getText());
        sfxTxtEditedBy.setText(sfxTxtEditedByDb.getText());
        sfxTxtSource.setText(sfxTxtSourceDb.getText());
    }

    /**
     * Reverts the data for this soundscape to the data in the db
     * @param evt
     */
    private void ssCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ssIdBox.setText(ssIdDbBox.getText());
        ssNameBox.setText(ssNameDbBox.getText());
        ssDescriptionBox.setText(ssDescriptionDbBox.getText());
        ssVolumeBox.setText(ssVolumeDbBox.getText());
    }

    /**
     * Saves changes to this keyword into the db
     * @param evt
     */
    private void kwSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        OperationsManager.db.setKeywordData(Integer.parseInt(kwIdBox.getText()), kwNameBox.getText());
    }

    /**
     * Saves changes for this sound file into the db
     * @param evt
     */
    private void sfxSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	int id = Integer.parseInt(sfxIdBox.getText());
    	String soundName = sfxNameBox.getText();
    	String description = sfxDescriptionBox.getText();
    	String dataFile = sfxDataBox.getText();
    	String length = sfxLengthBox.getText();
    	String owner = sfxOwnerBox.getText();
    	String copyrightIndex = String.valueOf(sfxComboBoxCopyright.getSelectedIndex());
    	String path = sfxPathBox.getText();
    	int fileSize = Integer.parseInt(sfxSizeBox.getText());
    	String importedBy = sfxTxtImportedBy.getText();
    	String sourceDesc = sfxTxtSource.getText();
    	String editedBy = sfxTxtEditedBy.getText();
    	
        OperationsManager.db.setSoundData(id, soundName, description, dataFile, length, owner, 
                copyrightIndex, path, fileSize, importedBy, sourceDesc, editedBy);
    }

    /**
     * Saves changes for this soundscape into the db
     * @param evt
     */
    private void ssSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        OperationsManager.db.setSoundscapeData(Integer.parseInt(ssIdBox.getText()), ssNameBox.getText(),
                ssDescriptionBox.getText(), Integer.parseInt(ssVolumeBox.getText()));
    }

    /**
     * Loads the selected keyword into the main window
     * @param evt
     */
    private void kwListMouseClicked(java.awt.event.MouseEvent evt) {
        ResultSet resultSet;
        int id = 0;
        String keyword = "";
        String search = kwList.getSelectedValue().toString();
        resultSet = OperationsManager.db.getKeywordData(search);
        try{
            while (resultSet.next()){
                id = resultSet.getInt(1);
                keyword = resultSet.getString(2);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        kwIdBox.setText(Integer.toString(id));
        kwIdDbBox.setText(Integer.toString(id));
        kwNameBox.setText(keyword);
        kwNameDbBox.setText(keyword);
    }

    private void kwListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        ResultSet resultSet;
        int id = 0;
        String keyword = "";
        String search = kwList.getSelectedValue().toString();
        resultSet = OperationsManager.db.getKeywordData(search);
        try{
            while (resultSet.next()){
                id = resultSet.getInt(1);
                keyword = resultSet.getString(2);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        kwIdBox.setText(Integer.toString(id));
        kwIdDbBox.setText(Integer.toString(id));
        kwNameBox.setText(keyword);
        kwNameDbBox.setText(keyword);
    }

    /**
     * Loads the selected sound file's data into the main window
     * @param evt
     */
    private void sfxListMouseClicked(java.awt.event.MouseEvent evt) {
        loadSFXValues();
    }

    private void sfxListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        loadSFXValues();
    }
    
    private void loadSFXValues(){
    	ResultSet resultSet;
        int id = 0, file_size=0;
        String name = "";
        String description = "";
        String data_file="";
        String length="";
        String owner="";
        String file_path="";
        String importedBy = "";
        String editedBy="";
        String source="";
        int copyrightIndex = 0;
        String search = sfxList.getSelectedValue().toString();
        resultSet = OperationsManager.db.getSoundData(search);
        try{
            while (resultSet.next()){
                id = resultSet.getInt(1);
                name = resultSet.getString(2);
                description = resultSet.getString(3);
                data_file = resultSet.getString(4);
                length = resultSet.getString(5);
                owner = resultSet.getString(6);
                String copyright = resultSet.getString(7);
                try{
                	copyrightIndex = Integer.parseInt(copyright);
                } catch (NumberFormatException e) {
                }
                file_path = resultSet.getString(8);
                file_size = resultSet.getInt(9);
                importedBy = resultSet.getString(10);
                source = resultSet.getString(11);
                editedBy = resultSet.getString(12);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        sfxIdBox.setText(Integer.toString(id));
        sfxNameBox.setText(name);
        sfxDescriptionBox.setText(description);
        sfxDataBox.setText(data_file);
        sfxLengthBox.setText(length);
        sfxOwnerBox.setText(owner);
        sfxComboBoxCopyright.setSelectedIndex(copyrightIndex);
        sfxPathBox.setText(file_path);
        sfxSizeBox.setText(Integer.toString(file_size));
        sfxIdDbBox.setText(Integer.toString(id));
        sfxNameDbBox.setText(name);
        sfxDescriptionDbBox.setText(description);
        sfxDataDbBox.setText(data_file);
        sfxLengthDbBox.setText(length);
        sfxOwnerDbBox.setText(owner);
        sfxComboBoxCopyrightDb.setSelectedIndex(copyrightIndex);
        sfxPathDbBox.setText(file_path);
        sfxSizeDbBox.setText(Integer.toString(file_size));
        sfxTxtImportedBy.setText(importedBy);
        sfxTxtEditedBy.setText(editedBy);
        sfxTxtSource.setText(source);
        sfxTxtImportedByDb.setText(importedBy);
        sfxTxtEditedByDb.setText(editedBy);
        sfxTxtSourceDb.setText(source);
    }

    /**
     * Loads the selected soundscape's data into the main window
     * @param evt
     */
    private void ssListMouseClicked(java.awt.event.MouseEvent evt) {
        ResultSet resultSet;
        int id = 0, volume=0;
        String name = "", description = "";
        String search = ssList.getSelectedValue().toString();
        resultSet = OperationsManager.db.getSoundscapeData(search);
        try{
            while (resultSet.next()){
                id = resultSet.getInt(1);
                name = resultSet.getString(2);
                description = resultSet.getString(3);
                volume = resultSet.getInt(4);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        ssIdBox.setText(Integer.toString(id));
        ssNameBox.setText(name);
        ssDescriptionBox.setText(description);
        ssVolumeBox.setText(Integer.toString(volume));
        ssIdDbBox.setText(Integer.toString(id));
        ssNameDbBox.setText(name);
        ssDescriptionDbBox.setText(description);
        ssVolumeDbBox.setText(Integer.toString(volume));
    }

    private void ssListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        ResultSet resultSet;
        int id = 0, volume=0;
        String name = "", description = "";
        String search = ssList.getSelectedValue().toString();
        resultSet = OperationsManager.db.getSoundscapeData(search);
        try{
            while (resultSet.next()){
                id = resultSet.getInt(1);
                name = resultSet.getString(2);
                description = resultSet.getString(3);
                volume = resultSet.getInt(4);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        ssIdBox.setText(Integer.toString(id));
        ssNameBox.setText(name);
        ssDescriptionBox.setText(description);
        ssVolumeBox.setText(Integer.toString(volume));
        ssIdDbBox.setText(Integer.toString(id));
        ssNameDbBox.setText(name);
        ssDescriptionDbBox.setText(description);
        ssVolumeDbBox.setText(Integer.toString(volume));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeDB().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kwCancelButton;
    private javax.swing.JLabel kwChangeDataLabel;
    private javax.swing.JPanel kwDataPanel;
    private javax.swing.JLabel kwDatabaseDataLabel;
    private javax.swing.JTextField kwIdBox;
    private javax.swing.JTextField kwIdDbBox;
    private javax.swing.JLabel kwIdDbLabel;
    private javax.swing.JLabel kwIdLabel;
    private javax.swing.JList<String> kwList;
    private javax.swing.JTextField kwNameBox;
    private javax.swing.JTextField kwNameDbBox;
    private javax.swing.JLabel kwNameDbLabel;
    private javax.swing.JLabel kwNameLabel;
    private javax.swing.JButton kwSaveButton;
    private javax.swing.JScrollPane kwScroll;
    private javax.swing.JPanel kwSelectPanel;
    private javax.swing.JPanel kwTab;
    private javax.swing.JButton sfxCancelButton;
    private javax.swing.JLabel sfxChangeDataLabel;
    private javax.swing.JLabel sfxCopyrightDbLabel;
    private javax.swing.JLabel sfxCopyrightLabel;
    private javax.swing.JTextField sfxDataBox;
    private javax.swing.JTextField sfxDataDbBox;
    private javax.swing.JLabel sfxDataDbLabel;
    private javax.swing.JLabel sfxDataLabel;
    private javax.swing.JPanel sfxDataPanel;
    private javax.swing.JLabel sfxDatabaseDataLabel;
    private javax.swing.JTextField sfxDescriptionBox;
    private javax.swing.JTextField sfxDescriptionDbBox;
    private javax.swing.JLabel sfxDescriptionDbLabel;
    private javax.swing.JLabel sfxDescriptionLabel;
    private javax.swing.JTextField sfxIdBox;
    private javax.swing.JTextField sfxIdDbBox;
    private javax.swing.JLabel sfxIdDbLabel;
    private javax.swing.JLabel sfxIdLabel;
    private javax.swing.JTextField sfxLengthBox;
    private javax.swing.JTextField sfxLengthDbBox;
    private javax.swing.JLabel sfxLengthDbLabel;
    private javax.swing.JLabel sfxLengthLabel;
    private javax.swing.JList<String> sfxList;
    private javax.swing.JTextField sfxNameBox;
    private javax.swing.JTextField sfxNameDbBox;
    private javax.swing.JLabel sfxNameDbLabel;
    private javax.swing.JLabel sfxNameLabel;
    private javax.swing.JTextField sfxOwnerBox;
    private javax.swing.JTextField sfxOwnerDbBox;
    private javax.swing.JLabel sfxOwnerDbLabel;
    private javax.swing.JLabel sfxOwnerLabel;
    private javax.swing.JTextField sfxPathBox;
    private javax.swing.JTextField sfxPathDbBox;
    private javax.swing.JLabel sfxPathDbLabel;
    private javax.swing.JLabel sfxPathLabel;
    private javax.swing.JButton sfxSaveButton;
    private javax.swing.JScrollPane sfxScroll;
    private javax.swing.JPanel sfxSelectPanel;
    private javax.swing.JTextField sfxSizeBox;
    private javax.swing.JTextField sfxSizeDbBox;
    private javax.swing.JLabel sfxSizeDbLabel;
    private javax.swing.JLabel sfxSizeLabel;
    private javax.swing.JPanel sfxTab;
    private javax.swing.JButton ssCancelButton;
    private javax.swing.JLabel ssChangeDataLabel;
    private javax.swing.JPanel ssDataPanel;
    private javax.swing.JLabel ssDatabaseDataLabel;
    private javax.swing.JTextField ssDescriptionBox;
    private javax.swing.JTextField ssDescriptionDbBox;
    private javax.swing.JLabel ssDescriptionDbLabel;
    private javax.swing.JLabel ssDescriptionLabel;
    private javax.swing.JTextField ssIdBox;
    private javax.swing.JTextField ssIdDbBox;
    private javax.swing.JLabel ssIdDbLabel;
    private javax.swing.JLabel ssIdLabel;
    private javax.swing.JList<String> ssList;
    private javax.swing.JTextField ssNameBox;
    private javax.swing.JTextField ssNameDbBox;
    private javax.swing.JLabel ssNameDbLabel;
    private javax.swing.JLabel ssNameLabel;
    private javax.swing.JButton ssSaveButton;
    private javax.swing.JScrollPane ssScroll;
    private javax.swing.JPanel ssSelectPanel;
    private javax.swing.JPanel ssTab;
    private javax.swing.JTextField ssVolumeBox;
    private javax.swing.JTextField ssVolumeDbBox;
    private javax.swing.JLabel ssVolumeDbLabel;
    private javax.swing.JLabel ssVolumeLabel;
    private GridBagConstraints gridBagConstraints_1;
    private JLabel sfxLblImportedBy;
    private GridBagConstraints gridBagConstraints_2;
    private GridBagConstraints gridBagConstraints_3;
    private GridBagConstraints gridBagConstraints_4;
    private GridBagConstraints gridBagConstraints_5;
    private GridBagConstraints gridBagConstraints_6;
    private GridBagConstraints gridBagConstraints_8;
    private GridBagConstraints gridBagConstraints_9;
    private GridBagConstraints gridBagConstraints_10;
    private GridBagConstraints gridBagConstraints_11;
    private GridBagConstraints gridBagConstraints_12;
    private GridBagConstraints gridBagConstraints_13;
    private GridBagConstraints gridBagConstraints_14;
    private GridBagConstraints gridBagConstraints_15;
    private GridBagConstraints gridBagConstraints_16;
    private GridBagConstraints gridBagConstraints_17;
    private GridBagConstraints gridBagConstraints_18;
    private GridBagConstraints gridBagConstraints_19;
    private GridBagConstraints gridBagConstraints_20;
    private GridBagConstraints gridBagConstraints_21;
    private GridBagConstraints gridBagConstraints_22;
    private GridBagConstraints gridBagConstraints_24;
    private GridBagConstraints gridBagConstraints_25;
    private GridBagConstraints gridBagConstraints_26;
    private GridBagConstraints gridBagConstraints_27;
    private GridBagConstraints gridBagConstraints_28;
    private GridBagConstraints gridBagConstraints_29;
    private JLabel sfxLblImportedByDb;
    private JLabel sfxLblSource;
    private JLabel sfxlblSourceDb;
    private JLabel sfxLblEditedBy;
    private JLabel sfxLblEditedByDb;
    private GridBagConstraints gridBagConstraints_30;
    private JTextField sfxTxtImportedBy;
    private JTextField sfxTxtSource;
    private JTextField sfxTxtEditedBy;
    private JTextField sfxTxtImportedByDb;
    private JTextField sfxTxtSourceDb;
    private JTextField sfxTxtEditedByDb;
    private JComboBox<String> sfxComboBoxCopyright;
    private JComboBox<String> sfxComboBoxCopyrightDb;
    // End of variables declaration//GEN-END:variables
    
}
